import { Command } from "#structures/classes/Command";
import { EmbedBuilder } from "discord.js";
import { player,ensurePlayer,resolve,add,success,error,dj,nowEmbed,rows,queueEmbed,parseTime,formatDuration,reply } from "#utils/MusicCore";
const aliases=["p","playskip","ps","pskip","playnow","pn","playtop","pt","pause","resume","join","summon","start","disconnect","dc","leave","stop","queue","q","search","skip","s","next","voteskip","forceskip","fs","fskip","skipto","st","shuffle","removedupes","rmd","rd","drm","leavecleanup","lc","control","c","ct","nowplaying","np","current","remove","rm","move","m","clear","volume","vol","loop","repeat","queueloop","qloop","seek","rewind","rwd","forward","fwd","replay","settings","setting","247","alwaysplaying","stay247","musichelp","mhelp"];
class Music extends Command{
constructor(){super({name:"play",description:"Rythm-style music system",usage:"play <song>",aliases,category:"Music",cooldown:2,enabledSlash:true,slashData:{name:"play",description:"Play a song or URL",options:[{name:"query",description:"Song name or URL",type:3,required:true}]}})}
async execute({client,message,args,prefix}){try{const raw=message.content.slice(prefix?.length||1).trim(),a=(raw.split(/\s+/)[0]||"play").toLowerCase();return this.run({client,message,args,a})}catch(e){return error({client,message,args},e.message)}}
async slashExecute({client,interaction}){try{return this.run({client,interaction,args:[],a:"play"})}catch(e){return error({client,interaction},e.message)}}
async run(c){
const a=c.a,args=c.args||[],q=c.interaction?.options.getString("query")||args.join(" ");
if(["play","p"].includes(a)){const r=await resolve(c,q),x=await add(c,r);return success(c,x.playlist?"📚 Playlist queued":"🎵 Now Playing",x.playlist?"Added "+x.count+" tracks.":"**"+x.track.info.title+"** — "+(x.track.info.author||"Unknown"))}
const d=dj(c);
if(["join","summon","start"].includes(a)){await ensurePlayer(c);return success(c,"🔊 Joined voice","LightCore is ready.")}
if(["playskip","ps","pskip","playnow","pn"].includes(a)){if(d)throw Error(d);const x=await add(c,await resolve(c,q),{skip:true});return success(c,"⏭️ Playing now","**"+x.track.info.title+"**")}
if(["playtop","pt"].includes(a)){if(d)throw Error(d);const x=await add(c,await resolve(c,q),{position:0});return success(c,"⬆️ Added to top","**"+x.track.info.title+"**")}
const p=player(c);
if(["pause","resume"].includes(a)){if(d)throw Error(d);if(!p?.currentTrack)throw Error("Nothing is playing.");if(a==="pause")await p.pause();else await p.resume();return success(c,a==="pause"?"⏸️ Paused":"▶️ Resumed","Done.")}
if(["disconnect","dc","leave","stop"].includes(a)){if(d)throw Error(d);if(!p)return success(c,"👋 Disconnected","Nothing is playing.");await p.stop();return success(c,"⏹️ Stopped","Playback stopped and the queue was cleared.")}
if(["queue","q"].includes(a)){if(!p?.currentTrack&&!p?.queueSize)throw Error("Queue is empty.");return reply(c,{embeds:[queueEmbed(p)]})}
if(["nowplaying","np","current","control","c","ct"].includes(a)){if(!p?.currentTrack)throw Error("Nothing is playing.");return reply(c,{embeds:[nowEmbed(p)],components:rows(p)})}
if(a==="search"){const r=await resolve(c,q),e=new EmbedBuilder().setColor(0x5865F2).setTitle("🔎 LightCore • Search").setDescription(r.tracks.slice(0,5).map((t,i)=>"**"+(i+1)+".** "+t.info.title+" — "+(t.info.author||"Unknown")+" • "+formatDuration(t.info.duration)).join("\n"));return reply(c,{embeds:[e]})}
if(["skip","s","next","voteskip","forceskip","fs","fskip"].includes(a)){if(d)throw Error(d);if(!p?.currentTrack)throw Error("Nothing is playing.");await p.skip();return success(c,"⏭️ Skipped","Next track started.")}
if(a==="clear"){if(d)throw Error(d);if(!p)throw Error("No active player.");const n=p.queueSize;await p.clearQueue();return success(c,"🧹 Queue cleared",n+" queued songs removed.")}
if(a==="shuffle"){if(d)throw Error(d);if(!p?.queueSize)throw Error("Queue is empty.");await p.shuffleQueue();return success(c,"🔀 Shuffled","Queue randomized.")}
if(["remove","rm"].includes(a)){if(d)throw Error(d);const n=Number(c.interaction?.options.getInteger("position")||args[0]);if(!p||!n||n>p.queueSize)throw Error("Invalid position.");const t=p.queue.tracks[n-1];await p.removeTrack(n-1);return success(c,"🗑️ Removed","**"+t.info.title+"**")}
if(["move","m"].includes(a)){if(d)throw Error(d);const n=Number(c.interaction?.options.getInteger("from")||args[0]),to=Number(c.interaction?.options.getInteger("to")||args[1]||1);if(!p||!n||n>p.queueSize||to<1||to>p.queueSize)throw Error("Invalid position.");await p.moveTrack(n-1,to-1);return success(c,"↕️ Queue updated",n+" → "+to)}
if(["skipto","st"].includes(a)){if(d)throw Error(d);const n=Number(c.interaction?.options.getInteger("position")||args[0]);if(!p?.currentTrack||!n||n<1||n>p.queueSize)throw Error("Invalid position.");await p.skip(n-1);return success(c,"⏭️ Skipped to",String(n))}
if(["removedupes","rmd","rd","drm"].includes(a)){if(d)throw Error(d);if(!p?.queueSize)throw Error("Queue is empty.");const seen=new Set();let n=0;for(let i=p.queue.tracks.length-1;i>=0;i--){const t=p.queue.tracks[i],k=(t.info.identifier||t.info.uri||t.info.title||"").toLowerCase();if(seen.has(k)){await p.removeTrack(i);n++}else seen.add(k)}return success(c,"🧹 Duplicates removed",n+" removed.")}
if(["leavecleanup","lc"].includes(a)){if(d)throw Error(d);const v=c.message?.member?.voice?.channel||c.interaction?.member?.voice?.channel;if(!p?.queueSize||!v)throw Error("Queue is empty or you are not in voice.");let n=0;for(let i=p.queue.tracks.length-1;i>=0;i--){const id=p.queue.tracks[i].requester?.id;if(id&&!v.members.has(id)){await p.removeTrack(i);n++}}return success(c,"🧹 Leave cleanup",n+" removed.")}
if(["volume","vol"].includes(a)){if(d&&args.length)throw Error(d);if(!p)throw Error("No active player.");const n=Number(c.interaction?.options.getInteger("level")||args[0]);if(!n)return success(c,"🔊 Volume",(p.volume??100)+"%");const v=Math.max(1,Math.min(200,n));await p.setVolume(v);return success(c,"🔊 Volume",v+"%")}
if(["loop","repeat","queueloop","qloop"].includes(a)){if(d)throw Error(d);if(!p?.currentTrack)throw Error("Nothing is playing.");const queue=a==="queueloop"||a==="qloop",m=queue?"queue":"track",n=p.repeatMode===m?"off":m;await p.setRepeatMode(n);return success(c,"🔁 Loop",n==="off"?"Disabled.":queue?"Queue loop enabled.":"Track loop enabled.")}
if(["seek","rewind","rwd","forward","fwd","replay"].includes(a)){if(d)throw Error(d);if(!p?.currentTrack)throw Error("Nothing is playing.");if(a==="replay"){await p.replay();return success(c,"🔄 Replay","Song restarted.")}const ms=parseTime(c.interaction?.options.getString("time")||args.join(" "));if(ms===null)throw Error("Give a valid time.");if(a==="seek")await p.seek(ms);if(["rewind","rwd"].includes(a))await p.rewind(ms);if(["forward","fwd"].includes(a))await p.forward(ms);return success(c,"⏱️ Playback moved",formatDuration(ms))}
if(["settings","setting"].includes(a)){if(!c.message?.member?.permissions?.has("ManageGuild")&&!c.interaction?.member?.permissions?.has("ManageGuild"))throw Error("Manage Server permission required.");return reply(c,{embeds:[new EmbedBuilder().setColor(0x5865F2).setTitle("⚙️ LightCore Music Settings").setDescription("DJ permissions are respected by playback controls.") ]})}
if(["247","alwaysplaying","stay247"].includes(a)){if(d)throw Error(d);const enabled=!/^(off|false|no)$/i.test(args[0]||"on"),guild=c.message?.guild||c.interaction?.guild;if(enabled){await ensurePlayer(c);const v=c.message?.member?.voice?.channel||c.interaction?.member?.voice?.channel;c.client.db.guild.set247Mode(guild.id,true,v.id,c.channel.id)}else c.client.db.guild.set247Mode(guild.id,false,null,null);return success(c,"♾️ 24/7",enabled?"Enabled.":"Disabled.")}
if(["musichelp","mhelp"].includes(a))return reply(c,{embeds:[new EmbedBuilder().setColor(0x5865F2).setTitle("🎵 LightCore Music").setDescription("Rythm-style music system").addFields({name:"Playback",value:".play .playskip .playtop .pause .resume .join .stop .skip .forceskip"},{name:"Queue",value:".queue .search .remove .move .clear .shuffle .skipto .removedupes .leavecleanup"},{name:"Controls",value:".nowplaying .control .volume .loop .queueloop .seek .rewind .forward .replay"},{name:"Server",value:".settings .247"})]});
throw Error("Unknown music command. Use .musichelp.");
}}
export default new Music();
