import { Command } from "#structures/classes/Command";
import { EmbedBuilder } from "discord.js";
import { db } from "#database/DatabaseManager";
import { fmt,parseTime,pm,send,err,ok,control,ensure,now,rows,play,settings,setSetting,COLOR } from "#utils/RythmMusic";
const A=["p","playskip","ps","pskip","playnow","pn","playtop","pt","pause","resume","join","summon","start","disconnect","dc","leave","stop","queue","q","remove","rm","move","m","clear","skip","s","next","voteskip","vs","forceskip","fs","fskip","skipto","st","shuffle","removedupes","rmd","rd","drm","leavecleanup","lc","control","c","ct","nowplaying","np","current","seek","rewind","rwd","forward","fwd","replay","loop","repeat","queueloop","qloop","volume","vol","search","settings","setting","247","alwaysplaying","stay247","musichelp","mhelp"];
class Music extends Command{
constructor(){super({name:"play",description:"Rythm-style music player",usage:"play <song>",aliases:A,category:"music",cooldown:2,enabledSlash:true,slashData:{name:"play",description:"Play a song",options:[{name:"query",description:"Song name or URL",type:3,required:true}]}})}
async execute({client,message,args,prefix}){try{const raw=message.content.slice(prefix?.length||1).trim(),a=(raw.split(/\s+/)[0]||"play").toLowerCase();return this.run(client,message,args,a)}catch(e){return err(message,e.message)}}
async slashExecute({client,interaction}){try{return this.run(client,interaction,[interaction.options.getString("query")||""],"play")}catch(e){return err(interaction,e.message)}}
async run(c,x,args,a){
if(a==="play"||a==="p"){const q=args.join(" ");if(!q)return err(x,"Give me a song name or URL.");const r=await play(x,c,q);return ok(x,r.playlist?"Playlist queued":r.playing?"Now playing":"Added to queue",r.playlist?"Added "+r.count+" tracks.":"**"+r.track.info.title+"**")}
if(["playskip","ps","pskip","playnow","pn"].includes(a)){const z=control(x);if(z)return err(x,z);const r=await play(x,c,args.join(" "),"skip");return ok(x,"Playing now","⏭️ "+r.track.info.title)}
if(["playtop","pt"].includes(a)){const z=control(x);if(z)return err(x,z);const r=await play(x,c,args.join(" "),"top");return ok(x,"Added to top","⬆️ "+r.track.info.title)}
if(["join","summon","start"].includes(a)){await ensure(x,c);return ok(x,"Joined voice","🔊 Ready.")}
const z=control(x);if(z&&!["search","musichelp","mhelp"].includes(a))return err(x,z);
const p=pm(x,c);
if(["pause","resume"].includes(a)){if(!p?.hasCurrentTrack)return err(x,"Nothing is playing.");if(a==="pause"&&!p.isPaused)await p.pause();else await p.resume();return ok(x,p.isPaused?"Paused":"Resumed",p.isPaused?"⏸️":"▶️")}
if(["disconnect","dc","leave","stop"].includes(a)){if(!p)return ok(x,"Disconnected","Not connected.");await p.stop();return ok(x,"Stopped","⏹️ Queue cleared.")}
if(["queue","q"].includes(a)){if(!p?.hasCurrentTrack)return err(x,"Queue is empty.");const t=p.queue.tracks.slice(0,10).map((v,i)=>"**"+(i+1)+".** "+v.info.title+" — "+fmt(v.info.duration)).join("\n")||"Queue is empty.";return send(x,now(p.player).setTitle("📜 LightCore • Queue").addFields({name:"Up next",value:t}))}
if(["nowplaying","np","current","control","c","ct"].includes(a)){if(!p?.hasCurrentTrack)return err(x,"Nothing is playing.");return send(x,now(p.player),rows(p.isPaused))}
if(["skip","s","next","voteskip","vs","forceskip","fs","fskip"].includes(a)){if(!p?.hasCurrentTrack)return err(x,"Nothing is playing.");await p.skip();return ok(x,"Skipped","⏭️ Track skipped.")}
if(a==="clear"){if(!p)return err(x,"No active player.");await p.clearQueue();return ok(x,"Queue cleared","🧹 Removed queued tracks.")}
if(a==="shuffle"){if(!p?.queueSize)return err(x,"Queue is empty.");await p.shuffleQueue();return ok(x,"Shuffled","🔀 Queue randomized.")}
if(["remove","rm"].includes(a)){const n=Number(args[0]);if(!p||!n||n>p.queueSize)return err(x,"Invalid position.");const t=p.queue.tracks[n-1];await p.removeTrack(n-1);return ok(x,"Removed","🗑️ "+t.info.title)}
if(["move","m"].includes(a)){const n=Number(args[0]),to=Number(args[1]||1);if(!p||!n||n>p.queueSize)return err(x,"Invalid position.");await p.moveTrack(n-1,to-1);return ok(x,"Queue updated","↕️ "+n+" → "+to)}
if(["skipto","st"].includes(a)){const n=Number(args[0]);if(!p||!n||n>p.queueSize)return err(x,"Invalid position.");await p.skip(n);return ok(x,"Skipped","⏭️ Position "+n)}
if(["volume","vol"].includes(a)){if(!p)return err(x,"No active player.");const n=Number(args[0]);if(!n)return ok(x,"Volume",String(p.volume)+"%");await p.setVolume(Math.max(1,Math.min(200,n)));return ok(x,"Volume","🔊 "+Math.max(1,Math.min(200,n))+"%")}
if(["loop","repeat","queueloop","qloop"].includes(a)){if(!p?.hasCurrentTrack)return err(x,"Nothing is playing.");const q=a==="queueloop"||a==="qloop",m=q?"queue":"track",n=p.repeatMode===m?"off":m;await p.setRepeatMode(n);return ok(x,"Loop",n==="off"?"➡️ Disabled.":q?"🔁 Queue loop enabled.":"🔂 Track loop enabled.")}
if(["seek","rewind","rwd","forward","fwd","replay"].includes(a)){if(!p?.hasCurrentTrack)return err(x,"Nothing is playing.");if(a==="replay"){await p.replay();return ok(x,"Replaying","🔄 Restarted.")}const ms=parseTime(args.join(" "));if(ms===null)return err(x,"Give a valid time.");if(a==="seek")await p.seek(ms);if(["rewind","rwd"].includes(a))await p.rewind(ms);if(["forward","fwd"].includes(a))await p.forward(ms);return ok(x,"Playback moved","⏱️ "+fmt(ms))}
if(["removedupes","rmd","rd","drm"].includes(a)){if(!p?.queueSize)return err(x,"Queue is empty.");const seen=new Set();let n=0;for(let i=p.queue.tracks.length-1;i>=0;i--){const t=p.queue.tracks[i],k=(t.info.identifier||t.info.uri||t.info.title).toLowerCase();if(seen.has(k)){await p.removeTrack(i);n++}else seen.add(k)}return ok(x,"Duplicates removed","🧹 "+n+" removed.")}
if(["leavecleanup","lc"].includes(a)){if(!p?.queueSize)return err(x,"Queue is empty.");const vc=x.member?.voice?.channel;if(!vc)return err(x,"Join voice first.");let n=0;for(let i=p.queue.tracks.length-1;i>=0;i--){const id=p.queue.tracks[i].requester?.id;if(id&&!vc.members.has(id)){await p.removeTrack(i);n++}}return ok(x,"Leave cleanup","🧹 "+n+" removed.")}
if(a==="search"){const q=args.join(" ");const r=await c.music.search(q,{source:"ytsearch",requester:x.user||x.author});if(!r?.tracks?.length)return err(x,"No results.");return send(x,new EmbedBuilder().setColor(COLOR).setTitle("🔎 Search").setDescription(r.tracks.slice(0,5).map((t,i)=>"**"+(i+1)+".** "+t.info.title+" — "+(t.info.author||"Unknown")+" • "+fmt(t.info.duration)).join("\n")))}
if(["settings","setting"].includes(a)){if(!x.member?.permissions?.has?.("ManageGuild"))return err(x,"Manage Server permission required.");const g=x.guild.id,s=settings(g),o=(args[0]||"").toLowerCase(),v=args.slice(1).join(" ");if(!o)return send(x,new EmbedBuilder().setColor(COLOR).setTitle("⚙️ Music Settings").setDescription("DJ role: "+(s.dj_role?"<@&"+s.dj_role+">":"Disabled")+"\nAutoplay: "+!!s.autoplay+"\nAnnouncements: "+!!s.announce+"\nVote skip: "+!!s.voteskip+"\n24/7: "+!!s.mode247+"\nSource: "+s.source+"\nDefault volume: "+s.volume+"%"));if(o==="djrole")setSetting(g,"dj_role",v.replace(/[^0-9]/g,"")||null);else if(["autoplay","announcesongs","voteskip"].includes(o))setSetting(g,o==="announcesongs"?"announce":o,/^(on|true|yes)$/i.test(v)?1:0);else if(o==="source")setSetting(g,"source",v||"ytsearch");else if(o==="defaultvolume")setSetting(g,"volume",Math.max(1,Math.min(100,Number(v)||100)));else if(o==="247"){const on=/^(on|true|yes)$/i.test(v),vc=x.member.voice.channel;if(on&&!vc)return err(x,"Join voice first.");setSetting(g,"mode247",on?1:0);db.guild.set247Mode(g,on,vc?.id||null,on?x.channel.id:null)}else return err(x,"Unknown setting.");return ok(x,"Settings saved","Updated.")}
if(["247","alwaysplaying","stay247"].includes(a)){const on=/^(on|true|yes)$/i.test(args[0]||"on"),vc=x.member.voice.channel;if(on&&!vc)return err(x,"Join voice first.");db.guild.set247Mode(x.guild.id,on,vc?.id||null,on?x.channel.id:null);return ok(x,"24/7",on?"🌙 Enabled.":"☀️ Disabled.")}
if(["musichelp","mhelp"].includes(a))return send(x,new EmbedBuilder().setColor(COLOR).setTitle("🎵 LightCore Music").setDescription("Rythm-style music system").addFields({name:"Playback",value:".play .playskip .playtop .pause .resume .skip .stop"},{name:"Queue",value:".queue .shuffle .clear .remove .move .skipto .removedupes"},{name:"Controls",value:".np .control .volume .loop .queueloop .seek .rewind .forward .replay"},{name:"Server",value:".settings .247 .join .disconnect .search"}));
return err(x,"Unknown music command. Use .musichelp.");
}}
export default new Music();