import { LavalinkManager } from "lavalink-client";
import { logger } from "#utils/logger";
import { config } from "#config/config";
import { db } from "#database/DatabaseManager";
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
export class MusicManager{
constructor(client){this.client=client;this.initialized=false;this.readyPromise=null;this.lastNodeWarning=0;this.init()}
init(){this.lavalink=new LavalinkManager({nodes:(config.nodes||[]).map(n=>({...n,retryAmount:Infinity,retryDelay:5000,resumeTimeout:120000})),sendToShard:(guildId,payload)=>{if(this.client.cluster)return this.client.cluster.broadcastEval((client,ctx)=>{const g=client.guilds.cache.get(ctx.guildId);if(!g)return false;g.shard?.send(ctx.payload);return true},{context:{guildId,payload}});return this.client.guilds.cache.get(guildId)?.shard?.send(payload)},autoSkip:true,autoSkipOnResolveError:true,emitNewSongsOnly:false,client:{id:config.clientId||this.client.user?.id,username:this.client.user?.username||"LightCore"},playerOptions:{maxErrorsPerTime:{threshold:15000,maxAmount:5},defaultSearchPlatform:"ytsearch",onDisconnect:{autoReconnect:true,destroyPlayer:false},onEmptyQueue:{destroyAfterMs:60000},useUnresolvedData:true,requesterTransformer:r=>r},queueOptions:{maxPreviousTracks:50},linksAllowed:true,linksBlacklist:[],linksWhitelist:[]});this.readyPromise=new Promise(resolve=>this.client.once("clientReady",async()=>{try{await this.lavalink.init({id:this.client.user.id,username:this.client.user.username})}catch(e){logger.error("MusicManager","Lavalink initialization failed",e)}finally{this.initialized=true;resolve()}}))}
getUsableNodes(){try{return this.lavalink?.nodeManager?.leastUsedNodes("players")||[]}catch{return[]}}
async waitForNode(timeout=12000){if(!this.initialized&&this.readyPromise)await Promise.race([this.readyPromise,sleep(timeout)]);const started=Date.now();while(Date.now()-started<timeout){const n=this.getUsableNodes();if(n.length)return n;await sleep(500)}if(Date.now()-this.lastNodeWarning>30000){this.lastNodeWarning=Date.now();logger.warn("MusicManager","No usable Lavalink node is connected.")}return[]}
isUrl(v){try{new URL(String(v));return true}catch{return false}}
normalizeSource(s="ytsearch"){const m={yt:"ytsearch",youtube:"ytsearch",ytm:"ytmsearch",youtubemusic:"ytmsearch",sp:"spsearch",spotify:"spsearch",sc:"scsearch",soundcloud:"scsearch"};return m[String(s).toLowerCase()]||s}
async createPlayer({guildId,textChannelId,voiceChannelId}){if(!guildId||!textChannelId||!voiceChannelId)return null;const old=this.lavalink?.getPlayer(guildId);if(old){if(old.voiceChannelId!==voiceChannelId)await old.connect().catch(()=>{});return old}const nodes=await this.waitForNode();if(!nodes.length)return null;let volume=100;try{volume=Number(db.guild.getDefaultVolume(guildId))||100}catch{}volume=Math.max(1,Math.min(200,volume));try{const p=await this.lavalink.createPlayer({guildId,voiceChannelId,textChannelId,selfDeaf:true,selfMute:false,volume});if(!p)return null;if(!p.connected)await p.connect();return p}catch(e){logger.error("MusicManager","Player creation failed: "+e.message);return null}}
async search(query,{source="ytsearch",requester}={}){const nodes=await this.waitForNode();if(!nodes.length)return null;const src=this.normalizeSource(source);for(const node of nodes){for(const s of [...new Set([src,...(src==="ytsearch"?["ytmsearch"]:[])])]){try{const r=await node.search({query,source:s},requester);if(r?.tracks?.length||r?.loadType==="playlist")return r}catch(e){logger.debug("MusicManager","Search failed on "+node.id+"/"+s+": "+e.message)}}}return null}
async resolve(query,options={}){if(!query)return null;if(!this.isUrl(query))return this.search(query,options);const nodes=await this.waitForNode();if(!nodes.length)return null;for(const node of nodes){try{const r=await node.search({query,source:options.source||"ytsearch"},options.requester);if(r?.tracks?.length||r?.loadType==="playlist")return r}catch(e){logger.debug("MusicManager","URL resolve failed: "+e.message)}}return null}
getPlayer(guildId){return this.lavalink?.getPlayer(guildId)||null}
getDefaultVolume(guildId){try{return db.guild.getDefaultVolume(guildId)||100}catch{return 100}}
setDefaultVolume(guildId,v){try{db.guild.setDefaultVolume(guildId,v);return true}catch{return false}}
async is247ModeEnabled(guildId){try{return db.guild.get247Settings(guildId).enabled===true}catch{return false}}
}