import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder } from "discord.js";
import { PlayerManager } from "#managers/PlayerManager";
export const MUSIC_COLOR=0x5865F2,ERROR_COLOR=0xED4245;
export const formatDuration=ms=>{if(ms==null||ms<0||!Number.isNaN(Number(ms))===false)return"LIVE";const t=Math.floor(ms/1000),h=Math.floor(t/3600),m=Math.floor(t%3600/60),s=t%60;return h?h+":"+String(m).padStart(2,"0")+":"+String(s).padStart(2,"0"):m+":"+String(s).padStart(2,"0")};
export const parseTime=v=>{v=String(v??"").trim().toLowerCase();if(!v)return null;if(/^\d+:\d+(?::\d+)?$/.test(v)){const a=v.split(":").map(Number);return(a.length===2?(a[0]*60+a[1]):(a[0]*3600+a[1]*60+a[2]))*1000}let t=0,m,re=/(\d+)\s*(h|hr|hour|hours|m|min|minute|minutes|s|sec|second|seconds)/g;while((m=re.exec(v)))t+=Number(m[1])*(m[2].startsWith("h")?3600000:m[2].startsWith("m")?60000:1000);return t||(/^\d+$/.test(v)?Number(v)*1000:null)};
export const ctx=x=>x.interaction?{client:x.client,source:x.interaction,guild:x.interaction.guild,member:x.interaction.member,user:x.interaction.user,channel:x.interaction.channel,args:[],slash:true}:{client:x.client,source:x.message,guild:x.message.guild,member:x.message.member,user:x.message.author,channel:x.message.channel,args:x.args||[],slash:false};
export const reply=async(x,p)=>{const c=ctx(x);return c.slash?(c.source.replied||c.source.deferred?c.source.editReply(p):c.source.reply(p)):c.source.reply(p)};
export const error=(x,m)=>reply(x,{embeds:[new EmbedBuilder().setColor(ERROR_COLOR).setTitle("🎵 LightCore Music").setDescription("❌ "+m)]});
export const success=(x,t,d)=>reply(x,{embeds:[new EmbedBuilder().setColor(MUSIC_COLOR).setTitle(t).setDescription(d||"")]});
export const voice=x=>ctx(x).member?.voice?.channel||null;
export const player=x=>{const c=ctx(x),p=c.guild&&c.client.music?.getPlayer(c.guild.id);return p?new PlayerManager(p):null};
export async function ensurePlayer(x){const c=ctx(x);if(!c.guild)throw Error("Music commands can only be used in a server.");const v=voice(x);if(!v)throw Error("Join a voice channel first.");let p=player(x);if(p?.voiceChannelId&&p.voiceChannelId!==v.id)throw Error("You must be in the same voice channel as LightCore.");if(!p){const raw=await c.client.music.createPlayer({guildId:c.guild.id,textChannelId:c.channel.id,voiceChannelId:v.id});if(!raw)throw Error("Music is temporarily unavailable because no Lavalink node is connected.");p=new PlayerManager(raw)}if(!p.isConnected)await p.connect();return p}
export const settings=x=>{const c=ctx(x);try{return c.client.db.guild.getMusicSettings(c.guild.id)}catch{return{dj_role:null,announceSongs:true,autoplay:false,voteSkip:false,volume:100}}};
export const dj=x=>{const c=ctx(x);if(!c.guild)return"Server only.";if(c.member?.permissions?.has("Administrator")||c.member?.permissions?.has("ManageGuild"))return null;const r=settings(x).dj_role;return r&&!c.member?.roles?.cache?.has(r)?"You need the configured DJ role to control music.":null};
export async function resolve(x,q,source="ytsearch"){const c=ctx(x),s=String(q||"").trim();if(!s)throw Error("Give me a song name or URL.");const r=c.client.music.isUrl(s)?await c.client.music.resolve(s,{source,requester:c.user}):await c.client.music.search(s,{source,requester:c.user});if(!r?.tracks?.length)throw Error("No results found.");return r}
export async function add(x,r,{position,skip=false}={}){const p=await ensurePlayer(x),idle=!p.currentTrack&&!p.queueSize;if(r.loadType==="playlist")await p.addTracks(r.tracks,position);else await p.addTracks(r.tracks[0],position);if(idle)await p.play();else if(skip)await p.skip();return{p,track:r.tracks[0],count:r.tracks.length,playlist:r.loadType==="playlist"}}
export const nowEmbed=p=>{const t=p?.currentTrack;if(!t)return new EmbedBuilder().setColor(ERROR_COLOR).setTitle("🎵 Nothing is playing");const d=t.info.duration||0,pos=Number(p.position||0),n=d?Math.round(Math.min(1,pos/d)*18):0;return new EmbedBuilder().setColor(MUSIC_COLOR).setTitle("🎵 LightCore • Now Playing").setDescription("**"+(t.info.title||"Unknown")+"**\n"+(t.info.author||"Unknown artist")).addFields({name:"Progress",value:"▰".repeat(n)+"▱".repeat(18-n)+"\n"+formatDuration(pos)+" / "+formatDuration(d)},{name:"Volume",value:(p.volume??100)+"%",inline:true},{name:"Loop",value:p.repeatMode||"off",inline:true},{name:"Queue",value:p.queueSize+" upcoming",inline:true})};
export const rows=p=>[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("lc_music_previous").setEmoji("⏮️").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("lc_music_pause").setEmoji(p?.isPaused?"▶️":"⏸️").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("lc_music_skip").setEmoji("⏭️").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("lc_music_stop").setEmoji("⏹️").setStyle(ButtonStyle.Danger)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("lc_music_shuffle").setEmoji("🔀").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("lc_music_loop").setEmoji("🔁").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("lc_music_volume_down").setEmoji("🔉").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("lc_music_volume_up").setEmoji("🔊").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("lc_music_queue").setEmoji("📜").setStyle(ButtonStyle.Secondary))];
export const queueEmbed=p=>{const q=p.queue.tracks||[],body=q.slice(0,10).map((t,i)=>"**"+(i+1)+".** "+(t.info.title||"Unknown")+" — "+formatDuration(t.info.duration)).join("\n")||"No songs are waiting.";return new EmbedBuilder().setColor(MUSIC_COLOR).setTitle("📜 LightCore • Queue").setDescription((p.currentTrack?"🎵 **Playing:** "+p.currentTrack.info.title+"\n\n":"")+body).setFooter({text:q.length+" queued • "+formatDuration(q.reduce((n,t)=>n+(t.info.duration||0),0))+" queued duration"})};
