import { EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle } from "discord.js";
import { PlayerManager } from "#managers/PlayerManager";
import { db } from "#database/DatabaseManager";
export const COLOR=0x5865f2;
export const fmt=ms=>{if(!ms||ms<0)return"LIVE";const s=Math.floor(ms/1000),m=Math.floor(s/60)%60,h=Math.floor(s/3600);return h?String(h)+":"+String(m).padStart(2,"0")+":"+String(s%60).padStart(2,"0"):String(m)+":"+String(s%60).padStart(2,"0")};
export const parseTime=v=>{if(!v)return null;v=String(v).trim().toLowerCase();if(/^\d+:\d+(?::\d+)?$/.test(v)){const a=v.split(":").map(Number);return a.length===2?(a[0]*60+a[1])*1000:(a[0]*3600+a[1]*60+a[2])*1000}let t=0,m,r=/(\d+)\s*(h|m|s)/g;while(m=r.exec(v))t+=Number(m[1])*(m[2]==="h"?3600000:m[2]==="m"?60000:1000);return t||null};
export const pm=(ctx,c)=>{const p=c.music?.getPlayer(ctx.guild?.id);return p?new PlayerManager(p):null};
export const send=(ctx,e,components=[])=>ctx.isChatInputCommand?.()?(ctx.replied||ctx.deferred?ctx.editReply({embeds:[e],components}):ctx.reply({embeds:[e],components})):ctx.reply({embeds:[e],components});
export const err=(ctx,m)=>send(ctx,new EmbedBuilder().setColor(0xed4245).setTitle("🎵 LightCore Music").setDescription("❌ "+m));
export const ok=(ctx,t,m)=>send(ctx,new EmbedBuilder().setColor(COLOR).setTitle(t).setDescription(m));
export const control=ctx=>{if(!ctx.guild)return"Server only.";if(ctx.member?.permissions?.has?.("Administrator")||ctx.member?.permissions?.has?.("ManageGuild"))return null;const s=settings(ctx.guild.id);return s.dj_role&&!ctx.member?.roles?.cache?.has(s.dj_role)?"You need the configured DJ role to control music.":null};
export async function ensure(ctx,c){const v=ctx.member?.voice?.channel;if(!v)throw new Error("Join a voice channel first.");let p=c.music?.getPlayer(ctx.guild.id);if(p?.voiceChannelId&&p.voiceChannelId!==v.id)throw new Error("You must be in the same voice channel as LightCore.");if(!p)p=await c.music.createPlayer({guildId:ctx.guild.id,textChannelId:ctx.channel.id,voiceChannelId:v.id});if(!p)throw new Error("Music is unavailable because no Lavalink node is connected.");if(!p.connected)await p.connect();return new PlayerManager(p)}
export const now=p=>{const t=p?.queue?.current;if(!t)return new EmbedBuilder().setColor(0xed4245).setTitle("🎵 Nothing is playing");const d=t.info.duration||0,pos=Number(p.position||0),n=d?Math.round(Math.min(1,pos/d)*18):0;return new EmbedBuilder().setColor(COLOR).setTitle("🎵 LightCore • Now Playing").setDescription("**["+(t.info.title||"Unknown")+"]("+(t.info.uri||"https://discord.com")+")**\n"+(t.info.author||"Unknown artist")).addFields({name:"Progress",value:"▰".repeat(n)+"▱".repeat(18-n)+"\n"+fmt(pos)+" / "+fmt(d)},{name:"Volume",value:String(p.volume??100)+"%",inline:true},{name:"Repeat",value:String(p.repeatMode||"off"),inline:true})};
export const rows=paused=>[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("lc_music_prev").setEmoji("⏮️").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("lc_music_rewind").setEmoji("⏪").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("lc_music_pause").setEmoji(paused?"▶️":"⏸️").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId("lc_music_forward").setEmoji("⏩").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("lc_music_skip").setEmoji("⏭️").setStyle(ButtonStyle.Secondary)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("lc_music_shuffle").setEmoji("🔀").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("lc_music_loop").setEmoji("🔁").setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId("lc_music_stop").setEmoji("⏹️").setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId("lc_music_queue").setEmoji("📜").setStyle(ButtonStyle.Secondary))];
export async function play(ctx,c,q,mode="normal"){const p=await ensure(ctx,c),empty=p.queueSize===0&&!p.isPlaying,r=c.music.isUrl(q)?await c.music.resolve(q,{requester:ctx.user||ctx.author}):await c.music.search(q,{source:"ytsearch",requester:ctx.user||ctx.author});if(!r?.tracks?.length)throw new Error("No results found.");if(r.loadType==="playlist"){await p.addTracks(r.tracks);if(empty)await p.play();return{playlist:true,count:r.tracks.length,track:r.tracks[0]}}const t=r.tracks[0];await p.addTracks(t,mode==="top"?0:undefined);if(empty)await p.play();if(mode==="skip")await p.skip();return{track:t,playing:empty||mode==="skip"}}
export function settings(g){try{db.guild.exec("CREATE TABLE IF NOT EXISTS lightcore_music (guild_id TEXT PRIMARY KEY,dj_role TEXT,autoplay INTEGER DEFAULT 0,announce INTEGER DEFAULT 1,voteskip INTEGER DEFAULT 0,mode247 INTEGER DEFAULT 0,source TEXT DEFAULT 'ytsearch',volume INTEGER DEFAULT 100)");let x=db.guild.get("SELECT * FROM lightcore_music WHERE guild_id=?",[g]);if(!x){db.guild.exec("INSERT INTO lightcore_music(guild_id) VALUES(?)",[g]);x=db.guild.get("SELECT * FROM lightcore_music WHERE guild_id=?",[g])}return x}catch{return{dj_role:null,autoplay:0,announce:1,voteskip:0,mode247:0,source:"ytsearch",volume:100}}}
export function setSetting(g,k,v){settings(g);db.guild.exec("UPDATE lightcore_music SET "+k+"=? WHERE guild_id=?",[v,g])}
